{{- if and .Values.kafka.install (not .Values.global.externalKafka.enabled) }}
{{- if .Values.kafka.consulDiscovery }}
apiVersion: qubership.org/v1alpha1
kind: ConsulACL
metadata:
  name: kafka-consul-acl-config
  labels:
    {{- include "kafka.defaultLabels" . | nindent 4 }}
spec:
  acl:
    name: consul-acls
    json: >
      {
         "policies":[
            {
               "ID":"",
               "Name":"kafka_operator_policy",
               "Description":"Policy for kafka Service operator to register Kafka service in the Consul",
               "Rules":"service \"{{ template "kafka-service.registeredServiceName" . }}\" {policy = \"write\"}"
            }
         ],
         "roles":[
            {
               "ID":"",
               "Name":"kafka_operator_role",
               "Description":"Role for Kafka Service operator to register Kafka service in the Consul",
               "policy_names":[
                  "kafka_operator_policy"
               ]
            }
         ],
         "bind_rules":[
            {
               "BindName":"kafka_operator_role",
               "ServiceAccountName":"{{ template "kafka.serviceAccount" . }}"
            }
         ]
      }
{{- end }}
{{- end }}