{{ if and (or .Values.operator.kafkaUserConfigurator.enabled .Values.operator.akhqConfigurator.enabled .Values.operator.kmmConfiguratorEnabled) (ne (.Values.DISABLE_CRD | toString) "true")  }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kafka.name" . }}-crd-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- end }}