{{- if and .Values.kafka.install (not .Values.global.externalKafka.enabled) }}
{{- if (not .Values.operator.serviceAccount) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kafka.name" . }}-operator
  labels:
    {{- include "kafka.defaultLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs:
      - get
      - create
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
      - persistentvolumeclaims
      - secrets
      - serviceaccounts
    verbs:
      - get
      - create
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - {{ .Values.operator.apiGroup }}
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
{{- end }}
{{- end }}