{{ if and (not .Values.global.restrictedEnvironment) (or .Values.operator.kafkaUserConfigurator.enabled .Values.operator.akhqConfigurator.enabled .Values.operator.kmmConfiguratorEnabled) (ne (.Values.DISABLE_CRD | toString) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kafka.name" . }}-crd-init-{{ .Release.Namespace }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kafka.name" . }}-crd-init-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kafka.name" . }}-crd-init
    namespace: {{ .Release.Namespace }}
{{- end }}