{{ if and (not .Values.global.restrictedEnvironment) (or .Values.operator.kafkaUserConfigurator.enabled .Values.operator.akhqConfigurator.enabled .Values.operator.kmmConfiguratorEnabled) (ne (.Values.DISABLE_CRD | toString) "true")  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kafka.name" . }}-crd-init-{{ .Release.Namespace }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - update
{{- end }}
