{{- if and (eq (include "kafka-service.enableDisasterRecovery" .) "true") (and .Values.global.disasterRecovery.httpAuth.enabled (not .Values.global.disasterRecovery.httpAuth.restrictedEnvironment)) }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: token-review-kafka-crb-{{ .Release.Namespace }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kafka.name" . }}-service-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
{{- end }}