version: '2'
services:
  zookeeper:
    image: ghcr.io/netcracker/qubership-docker-zookeeper:main@sha256:738b927d4a6b75d3491325a6da728ddcdcfec864ac2534cd9c25ecdd2e96f95a
    ports:
      - 2181:2181
  kafka:
    image: ghcr.io/netcracker/qubership-docker-kafka:main@sha256:fe0fb45dacfb42d6165cd50c811f57c18eb791fd44404a5b9c98a4ff1c3f1271
    ports:
      - 9094:9094
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      - BROKER_ID=1
      - REPLICATION_FACTOR=3
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - DISABLE_SECURITY=true
      - READINESS_PERIOD=30
      - EXTERNAL_HOST_NAME=localhost
      - EXTERNAL_PORT=9094
      - CONF_KAFKA_MIN_INSYNC_REPLICAS=1
  akhq:
    image: ghcr.io/netcracker/qubership-docker-akhq:main@sha256:12b22c29a4e56c03e430c6c66e9d9f3dc664f9a5bbf9bf563d1acd0ed118f04b
    ports:
      - 8080:8080
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: "kafka:9092"
                security.protocol: PLAINTEXT