version: '2'
services:
  zookeeper:
    image: ghcr.io/netcracker/qubership-docker-zookeeper:main@sha256:39eb572e3edbf16cc197812cbcde4bbabd18983a90eb686ddb963c5df3fd090f
    ports:
      - 2181:2181
  kafka:
    image: ghcr.io/netcracker/qubership-docker-kafka:main@sha256:fe0fb45dacfb42d6165cd50c811f57c18eb791fd44404a5b9c98a4ff1c3f1271
    ports:
      - 9094:9094
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      - BROKER_ID=1
      - REPLICATION_FACTOR=3
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - DISABLE_SECURITY=true
      - READINESS_PERIOD=30
      - EXTERNAL_HOST_NAME=localhost
      - EXTERNAL_PORT=9094
      - CONF_KAFKA_MIN_INSYNC_REPLICAS=1
  akhq:
    image: ghcr.io/netcracker/qubership-docker-akhq:main@sha256:fe0834b7e1c65fb9f3137d843705c64d68ab350fb5fb1a729d19ee9287ffefb9
    ports:
      - 8080:8080
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: "kafka:9092"
                security.protocol: PLAINTEXT