{{- if .Values.backupDaemon.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kafka.name" . }}-backup-daemon
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
    component: kafka-backup-daemon
    name: {{ template "kafka.name" . }}-backup-daemon
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- end }}