{{- if .Values.backupDaemon.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka.name" . }}-backup-daemon-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  username: {{ .Values.global.secrets.backupDaemon.username | default "" | quote }}
  password: {{ .Values.global.secrets.backupDaemon.password | default "" | quote }}
{{- end }}