# permissions for end users to edit kafkaservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaservice-editor-role
rules:
- apiGroups:
  - netcracker.com
  resources:
  - kafkaservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netcracker.com
  resources:
  - kafkaservices/status
  verbs:
  - get
