# permissions for end users to edit kafkausers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkauser-editor-role
rules:
- apiGroups:
  - qubership.org
  resources:
  - kafkausers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qubership.org
  resources:
  - kafkausers/status
  verbs:
  - get
