# permissions for end users to view kafkausers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkauser-viewer-role
rules:
- apiGroups:
  - netcracker.com
  resources:
  - kafkausers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netcracker.com
  resources:
  - kafkausers/status
  verbs:
  - get
