# permissions for end users to view kmmconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmmconfig-viewer-role
rules:
- apiGroups:
  - qubership.org
  resources:
  - kmmconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qubership.org
  resources:
  - kmmconfigs/status
  verbs:
  - get
