{
 "title": "Kafka Monitoring",
 "description": "Kafka Monitoring",
 "tags": [
  "kafka",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kafka_controller_KafkaController_Value, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kafka_controller_KafkaController_Value{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(kafka_controller_KafkaController_Value{namespace=\"$namespace\", cluster=\"$cluster\"}, broker)"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Status",
   "type": "stat",
   "description": "Current status of Kafka cluster",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_cluster_status{namespace=\"$namespace\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "stat",
   "description": "Current size of Kafka cluster",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kafka_cluster_size{namespace=\"$namespace\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "description": "Current count of ready pods. May be not applicable for managed external Kafka.",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{exported_namespace=\"$namespace\", cluster=\"$cluster\", exported_pod=~\"$broker.*\", condition=\"true\"}) OR on() vector(-1)"
    }
   ]
  },
  {
   "title": "Controller State",
   "type": "stat",
   "description": "Current state of controller broker. The controller changes state when processing an event. Most of the time, the Idle state is displayed, which means that the controller has processed all the events. If the event processing takes a considerable time (several seconds or more), this state of the controller will be displayed. May be not applicable for managed external Kafka.",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_KafkaController_Value{name=\"ControllerState\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_cluster_quorum_mode{namespace=\"$namespace\"} == 101",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controller Broker",
   "type": "stat",
   "description": "Current controller broker.\nThe first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"ActiveControllerCount\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"} > 0",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Kafka Version",
   "type": "stat",
   "description": "Kafka version running on controller broker",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (kafka_server_app_info_Version{namespace=\"$namespace\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Cluster Status Transitions",
   "type": "state-timeline",
   "description": "Transitions of Kafka cluster statuses",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_cluster_status{namespace=\"$namespace\", cluster=\"$cluster\"})",
     "legendFormat": "Cluster State"
    }
   ]
  },
  {
   "title": "Controller State Transitions",
   "type": "state-timeline",
   "description": "Transitions of controller broker states. The controller changes state when processing an event. Most of the time, the Idle state is displayed, which means that the controller has processed all the events. If the event processing takes a considerable time (several seconds or more), this state of the controller will be displayed",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_controller_KafkaController_Value{name=\"ControllerState\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"})",
     "legendFormat": "Controller state"
    }
   ]
  },
  {
   "title": "Pod Readiness Probe Transitions",
   "type": "state-timeline",
   "description": "Transitions of readiness probes for each Kafka pod. May be not applicable for managed external Kafka.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(kube_pod_status_ready{exported_namespace=\"$namespace\", cluster=\"$cluster\", exported_pod=~\"$broker.*\", condition=\"true\"}) by (exported_pod)",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Similar Configs",
   "type": "stat",
   "description": "Information about brokers configuration consistency",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_cluster_status{namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "{{same_configs}}"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "table",
   "description": "Information about broker states, number of partitions replicas on each broker, number of partitions where current broker is a leader, skews and number of under replicated partitions",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_server_KafkaServer_Value{name=\"BrokerState\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)"
    },
    {
     "expr": "max(kafka_server_ReplicaManager_Value{name=\"PartitionCount\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)"
    },
    {
     "expr": "max(kafka_broker_skew{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)"
    },
    {
     "expr": "max(kafka_server_ReplicaManager_Value{name=\"LeaderCount\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)"
    },
    {
     "expr": "max(kafka_broker_leader_skew{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)"
    },
    {
     "expr": "max(kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)"
    },
    {
     "expr": "max(kafka_server_ReplicaManager_Value{name=\"UnderMinIsrPartitionCount\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)"
    }
   ]
  },
  {
   "title": "Broker Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "timeseries",
   "description": "The number of under-replicated partitions. Replicas that are added as part of a reassignment will not count toward this value",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\",namespace=\"$namespace\",cluster=\"$cluster\",broker=~\"$broker\"}",
     "legendFormat": "{{ broker }}"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "timeseries",
   "description": "The number of partitions whose in-sync replicas (ISR) count is less than `minIsr`",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"UnderMinIsrPartitionCount\",namespace=\"$namespace\",cluster=\"$cluster\",broker=~\"$broker\"}",
     "legendFormat": "{{ broker }}"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "timeseries",
   "description": "The number of partitions that don’t have an active leader and are hence not writable or readable",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"OfflinePartitionsCount\",namespace=\"$namespace\",cluster=\"$cluster\",broker=~\"$broker\"}",
     "legendFormat": "{{ broker }}"
    }
   ]
  },
  {
   "title": "Partitions With Late Transactions",
   "type": "timeseries",
   "description": "The number of partitions which have open transactions with durations exceeding `transaction.max.timeout.ms` (plus 5 minutes)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"PartitionsWithLateTransactionsCount\",namespace=\"$namespace\",cluster=\"$cluster\",broker=~\"$broker\"}",
     "legendFormat": "{{ broker }}"
    }
   ]
  },
  {
   "title": "Broker Errors Rate",
   "type": "timeseries",
   "description": "The rate of errors in responses counted per error code. If a response contains multiple errors, all are counted",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_RequestMetrics_Count_total{name=\"ErrorsPerSec\",error!=\"NONE\",namespace=\"$namespace\",cluster=\"$cluster\",broker=~\"$broker\"}[5m])) by (broker, error)",
     "legendFormat": "{{ broker }}: {{error}}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Topics Count",
     "type": "stat",
     "description": "Total number of topics on Kafka cluster. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kafka_controller_KafkaController_Value{name=\"GlobalTopicCount\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"})"
      }
     ]
    },
    {
     "title": "Total Partitions Count",
     "type": "stat",
     "description": "Total number of partitions on Kafka cluster. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kafka_controller_KafkaController_Value{name=\"GlobalPartitionCount\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"})"
      }
     ]
    },
    {
     "title": "Max Partitions Per Broker",
     "type": "stat",
     "description": "Number of max partitions per broker. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(max(kafka_server_ReplicaManager_Value{name=\"PartitionCount\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker))"
      }
     ]
    },
    {
     "title": "Topics Without Leader",
     "type": "stat",
     "description": "List of topics which have at least one partition without a leader. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kafka_cluster_topic_without_leader{namespace=\"$namespace\", cluster=\"$cluster\"}) OR on() vector(0)",
       "legendFormat": "{{topics_without_leader}}"
      }
     ]
    },
    {
     "title": "Offline Partitions Count",
     "type": "stat",
     "description": "Number of partitions without an active leader. Because all read and write operations are only performed on partition leaders, a non-zero value for this metric should be alerted on to prevent service interruptions. Any partition without an active leader will be completely inaccessible, and both consumers and producers of that partition will be blocked until a leader becomes available",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kafka_controller_KafkaController_Value{name=\"OfflinePartitionsCount\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"})"
      }
     ]
    },
    {
     "title": "Under Replicated Topics",
     "type": "stat",
     "description": "Count of topics which have at least one under replicated partition. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(group(kafka_cluster_Partition_Value{name=\"UnderReplicated\",namespace=\"$namespace\",cluster=\"$cluster\"} > 0) by (topic)) OR on() vector(0)"
      }
     ]
    },
    {
     "title": "Topics With Unclean Leader Election Enabled",
     "type": "stat",
     "description": "Count of topics with unclean leader election enabled. Unclean leader elections can lead to data loss, so you should check these topics to see if this setting is set reasonably. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kafka_cluster_unclean_election_topics{namespace=\"$namespace\", cluster=\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Consumer Groups Number",
     "type": "table",
     "description": "Number of consumer groups in different states. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(kafka_coordinator_group_GroupMetadataManager_Value{name=\"NumGroups\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (namespace)"
      },
      {
       "expr": "max(kafka_coordinator_group_GroupMetadataManager_Value{name=\"NumGroupsStable\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (namespace)"
      },
      {
       "expr": "max(kafka_coordinator_group_GroupMetadataManager_Value{name=\"NumGroupsPreparingRebalance\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (namespace)"
      },
      {
       "expr": "max(kafka_coordinator_group_GroupMetadataManager_Value{name=\"NumGroupsCompletingRebalance\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (namespace)"
      },
      {
       "expr": "max(kafka_coordinator_group_GroupMetadataManager_Value{name=\"NumGroupsEmpty\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (namespace)"
      },
      {
       "expr": "max(kafka_coordinator_group_GroupMetadataManager_Value{name=\"NumGroupsDead\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap and GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JVM Heap Usage",
     "type": "timeseries",
     "description": "JVM heap usage by broker. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(java_Memory_HeapMemoryUsage_used{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)",
       "legendFormat": "{{broker}}: used"
      },
      {
       "expr": "max(java_Memory_HeapMemoryUsage_max{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)",
       "legendFormat": "{{broker}}: limit"
      }
     ]
    },
    {
     "title": "JVM Heap Usage in Percent",
     "type": "timeseries",
     "description": "JVM heap usage by broker in percent (%). May be not applicable for managed external Kafka.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(max(java_Memory_HeapMemoryUsage_used{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker) / max(java_Memory_HeapMemoryUsage_max{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)) * 100",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "timeseries",
     "description": "Garbage collection time rate per second by broker. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(rate(java_GarbageCollector_CollectionTime_total{name=\"G1 Young Generation\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[$__interval])) by (broker) >= 0",
       "legendFormat": "{{broker}}: young"
      },
      {
       "expr": "max(rate(java_GarbageCollector_CollectionTime_total{name=\"G1 Old Generation\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[$__interval])) by (broker) >= 0",
       "legendFormat": "{{broker}}: old"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "timeseries",
     "description": "Garbage collections count rate per second by broker. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(rate(java_GarbageCollector_CollectionCount_total{name=\"G1 Young Generation\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[$__interval])) by (broker) >=0",
       "legendFormat": "{{broker}}: young"
      },
      {
       "expr": "max(rate(java_GarbageCollector_CollectionCount_total{name=\"G1 Old Generation\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[$__interval])) by (broker) >=0",
       "legendFormat": "{{broker}}: old"
      }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Memory usage by pod. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", cluster=\"$cluster\", pod=~\"$broker.*\", container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}: allocated"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", cluster=\"$cluster\", pod=~\"$broker.*\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}: usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", cluster=\"$cluster\", exported_pod=~\"$broker.*\"}) by (exported_pod)",
       "legendFormat": "{{exported_pod}}: limit"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "CPU usage by pod. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", cluster=\"$cluster\", pod=~\"$broker.*\", container!=\"\", image!=\"\"}[$__interval])) by (pod)) * 1000",
       "legendFormat": "{{pod}}: usage"
      },
      {
       "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=\"$namespace\", cluster=\"$cluster\", exported_pod=~\"$broker.*\"}) by (exported_pod)) * 1000",
       "legendFormat": "{{exported_pod}}: limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Read Bytes",
     "type": "timeseries",
     "description": "The total size in bytes of read operations on the volume for each broker. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(kafka_server_KafkaServer_Value{name=\"linux-disk-read-bytes\",namespace=\"${namespace}\",cluster=\"$cluster\",broker=~\"$broker\"}[5m])",
       "legendFormat": "{{ broker }}"
      }
     ]
    },
    {
     "title": "Disk Write Bytes",
     "type": "timeseries",
     "description": "The total size in bytes of write operations on the volume for each broker. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(kafka_server_KafkaServer_Value{name=\"linux-disk-write-bytes\",namespace=\"${namespace}\",cluster=\"$cluster\",broker=~\"$broker\"}[5m])",
       "legendFormat": "{{ broker }}"
      }
     ]
    },
    {
     "title": "Topic Partition Data Size",
     "type": "timeseries",
     "description": "The total size in bytes of volume space occupied by topic partitions logs for each broker. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_log_Log_Value{name=\"Size\",namespace=\"${namespace}\",cluster=\"$cluster\",broker=~\"$broker\"}) by (broker)",
       "legendFormat": "{{ broker }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Queue Size",
     "type": "timeseries",
     "description": "Total number of controller requests to be sent out to brokers",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(kafka_controller_ControllerChannelManager_Value{name=\"TotalQueueSize\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) >= 0",
       "legendFormat": "total_queue_size"
      }
     ]
    },
    {
     "title": "Event Queue Size",
     "type": "timeseries",
     "description": "Size of ControllerEventManager's queue. Every ControllerEvent has an associated state. When a ControllerEvent is processed, it triggers a state transition to the requested state. ControllerEvent events are managed by ControllerEventManager",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(kafka_controller_ControllerEventManager_Value{name=\"EventQueueSize\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) >= 0",
       "legendFormat": "event_queue_size"
      }
     ]
    },
    {
     "title": "Event Queue Time Rate",
     "type": "timeseries",
     "description": "Time it takes for any event (except the Idle event) to wait in the ControllerEventManager's queue before being processed",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(idelta(kafka_controller_ControllerEventManager_Count_total{name=\"EventQueueTimeMs\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[$__interval]))",
       "legendFormat": "event_queue_time_rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bytes In/Out",
     "type": "timeseries",
     "description": "Aggregate incoming/outgoing byte rate per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "max(rate(kafka_server_BrokerTopicMetrics_Count_total{name=\"BytesInPerSec\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[5m])) by (broker) >= 0",
       "legendFormat": "{{broker}}: in"
      },
      {
       "expr": "max(rate(kafka_server_BrokerTopicMetrics_Count_total{name=\"BytesOutPerSec\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[5m])) by (broker) >= 0",
       "legendFormat": "{{broker}}: out"
      }
     ]
    },
    {
     "title": "Bytes Rejected",
     "type": "timeseries",
     "description": "Amount of data in bytes per second rejected by broker",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "max(rate(kafka_server_BrokerTopicMetrics_Count_total{name=\"BytesRejectedPerSec\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[5m])) by (broker) >= 0",
       "legendFormat": "{{broker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ZooKeeper Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ZooKeeper Session State",
     "type": "table",
     "description": "ZooKeeper session state for each broker. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_server_SessionExpireListener_Value{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}"
      }
     ]
    },
    {
     "title": "ZooKeeper Requests Rate",
     "type": "timeseries",
     "description": "Rate of ZooKeeper requests. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_server_ZooKeeperClientMetrics_Count_total{name=\"ZooKeeperRequestLatencyMs\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[5m])",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Requests Latency",
     "type": "timeseries",
     "description": "Latency of ZooKeeper requests. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_server_ZooKeeperClientMetrics_95thPercentile{name=\"ZooKeeperRequestLatencyMs\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}",
       "legendFormat": "{{broker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "In Sync Replica (ISR)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Isr Expands Rate",
     "type": "timeseries",
     "description": "ISR expansion rate. If a broker goes down, ISR for some of the partitions will shrink. When that broker is up again, ISR will be expanded once the replicas are fully caught up. Other than that, the expected value for both ISR shrink rate and expansion rate is 0",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(idelta(kafka_server_ReplicaManager_Count_total{name=\"IsrExpandsPerSec\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[$__interval])) by (broker) >= 0",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "Isr Shrinks Rate",
     "type": "timeseries",
     "description": "ISR shrink rate. If a broker goes down, ISR for some of the partitions will shrink. When that broker is up again, ISR will be expanded once the replicas are fully caught up. Other than that, the expected value for both ISR shrink rate and expansion rate is 0",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(idelta(kafka_server_ReplicaManager_Count_total{name=\"IsrShrinksPerSec\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[$__interval])) by (broker) >= 0",
       "legendFormat": "{{broker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Message Rate",
     "type": "timeseries",
     "description": "Aggregate incoming messages rate per second",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(rate(kafka_server_BrokerTopicMetrics_Count_total{name=\"MessagesInPerSec\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[5m])) by (broker)",
       "legendFormat": "{{broker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Fetch Requests Rate",
     "type": "timeseries",
     "description": "Total fetch request rate per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(abs(rate(kafka_server_BrokerTopicMetrics_Count_total{name=\"TotalFetchRequestsPerSec\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[5m]))) by (broker)",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "Total Produce Requests Rate",
     "type": "timeseries",
     "description": "Total produce request rate per second",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(abs(rate(kafka_server_BrokerTopicMetrics_Count_total{name=\"TotalProduceRequestsPerSec\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\",}[5m]))) by (broker)",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "Failed Fetch Requests Rate",
     "type": "timeseries",
     "description": "Fetch request rate per second for requests that failed",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(rate(kafka_server_BrokerTopicMetrics_Count_total{name=\"FailedFetchRequestsPerSec\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[5m])) by (broker)",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "Failed Produce Requests Rate",
     "type": "timeseries",
     "description": "Produce request rate per second for requests that failed",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(rate(kafka_server_BrokerTopicMetrics_Count_total{name=\"FailedProduceRequestsPerSec\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[5m])) by (broker)",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "Fetch Queue Size",
     "type": "timeseries",
     "description": "Size of fetch queue. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(idelta(kafka_server_Fetch_queue_size{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[$__interval])) by (broker)",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "Request Queue Size",
     "type": "timeseries",
     "description": "Size of request queue. A congested request queue will not be able to process incoming or outgoing requests",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(idelta(kafka_network_RequestChannel_Value{name=\"RequestQueueSize\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}[$__interval])) by (broker)",
       "legendFormat": "{{broker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Thread Count",
     "type": "timeseries",
     "description": "Number of live threads, including both daemon and non-daemon threads. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(java_Threading_ThreadCount{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "Total Started Thread Count",
     "type": "timeseries",
     "description": "Total number of threads created and also started since the JVM started. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(java_Threading_TotalStartedThreadCount{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "Log Cleaner And Replica Fetcher Threads",
     "type": "table",
     "description": "Information about configured and dead Log Cleaner and Replica Fetcher threads. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "max(kafka_log_cleaner_threads_count{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)"
      },
      {
       "expr": "max(kafka_log_LogCleaner_Value{name=\"DeadThreadCount\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)"
      },
      {
       "expr": "max(kafka_replica_fetcher_threads_count{namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)"
      },
      {
       "expr": "max(kafka_server_ReplicaFetcherManager_Value{name=\"DeadThreadCount\", namespace=\"$namespace\", cluster=\"$cluster\", broker=~\"$broker\"}) by (broker)"
      }
     ]
    }
   ]
  }
 ]
}