{
 "title": "Kafka Topics",
 "description": "Kafka Topics",
 "tags": [
  "kafka",
  "prometheus",
  "kafka_topics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kafka_controller_KafkaController_Value, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kafka_controller_KafkaController_Value{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(kafka_controller_KafkaController_Value{namespace=\"$namespace\", cluster=\"$cluster\"}, brokerInstance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "query_result(count by (topic)(count_over_time(kafka_log_Log_Value{namespace=\"$namespace\", topic=~\"$topics_regex\", cluster=\"$cluster\", name=\"Size\"}[1h])))"
    }
   },
   { "name": "topics_regex", "label": "Topics Regex", "query": ".*" },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topics",
   "type": "table",
   "description": "The count of partitions, number of messages and size in bytes for each topic in descending order of size values",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(sum(kafka_log_Log_Value{name=\"LogEndOffset\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (topic, brokerInstance) - sum(kafka_log_Log_Value{name=\"LogStartOffset\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (topic, brokerInstance)) by (topic)"
    },
    {
     "expr": "max(sum(kafka_log_Log_Value{name=\"Size\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (topic, brokerInstance)) by (topic)"
    },
    {
     "expr": "max(count(kafka_log_Log_Value{name=\"Size\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (topic, brokerInstance)) by (topic)"
    }
   ]
  },
  {
   "title": "Topic Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Under Min ISR Partitions Table",
     "type": "table",
     "description": "The list of topic partitions whose in-sync replicas (ISR) count is less than `minIsr` for each broker",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_cluster_Partition_Value{name=\"UnderMinIsr\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (topic, partition) == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions Table",
     "type": "table",
     "description": "The number of topic under-replicated partitions for each broker",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_cluster_Partition_Value{name=\"UnderReplicated\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (topic, partition) == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unclean Election Leader Topics Table",
     "type": "table",
     "description": "List of topics with unclean leader election enabled. Unclean leader elections can lead to data loss, so you should check these topics to see if this setting is set reasonably. May be not applicable for managed external Kafka.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_cluster_unclean_election_topics{namespace=\"$namespace\", topic=~\"$topic\"}) by (topic)",
       "legendFormat": "{{ topic }} - {{ brokerInstance }}"
      }
     ]
    },
    {
     "title": "Partition Data Size",
     "type": "timeseries",
     "description": "The total size in bytes of volume space occupied by specific topic for each broker",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_log_Log_Value{name=\"Size\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (topic, brokerInstance)",
       "legendFormat": "{{ topic }} - {{ brokerInstance }}"
      }
     ]
    },
    {
     "title": "Under Min ISR Partitions",
     "type": "timeseries",
     "description": "The number of topic partitions whose in-sync replicas (ISR) count is less than `minIsr` for each broker",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_cluster_Partition_Value{name=\"UnderMinIsr\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (topic, brokerInstance)",
       "legendFormat": "{{ topic }} - {{ brokerInstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topics Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Messages Rate",
     "type": "timeseries",
     "description": "The incoming messages rate by specific topic for each broker. `No Data` for specific topic means that there are no operations performed on the topic",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max(rate(kafka_server_BrokerTopicMetrics_Count_total{name=\"MessagesInPerSec\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (topic, brokerInstance)",
       "legendFormat": "{{ topic }} - {{ brokerInstance }}"
      }
     ]
    },
    {
     "title": "Incoming Bytes Rate",
     "type": "timeseries",
     "description": "The incoming bytes rate by specific topic for each broker. `No Data` for specific topic means that there are no operations performed on the topic",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max(rate(kafka_server_BrokerTopicMetrics_Count_total{name=\"BytesInPerSec\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (topic, brokerInstance)",
       "legendFormat": "{{ topic }} - {{ brokerInstance }}"
      }
     ]
    },
    {
     "title": "Outgoing Bytes Rate",
     "type": "timeseries",
     "description": "The outgoing bytes rate by specific topic for each broker. `No Data` for specific topic means that there are no operations performed on the topic",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max(rate(kafka_server_BrokerTopicMetrics_Count_total{name=\"BytesOutPerSec\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (topic, brokerInstance)",
       "legendFormat": "{{ topic }} - {{ brokerInstance }}"
      }
     ]
    },
    {
     "title": "Partition Data Size",
     "type": "timeseries",
     "description": "The total size in bytes of volume space occupied by specific topic for each broker",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_log_Log_Value{name=\"Size\",topic=~\"$topic\",brokerInstance=~\"$broker\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (topic, brokerInstance)",
       "legendFormat": "{{ topic }} - {{ brokerInstance }}"
      }
     ]
    }
   ]
  }
 ]
}