{
 "title": "Kafka Mirror Maker Monitoring",
 "tags": [
  "Kafka Mirror Maker",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kmm_health_status_code, cluster)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(kmm_health_status_code{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "target",
    "label": "Target",
    "query": "label_values(replication_latency_replication_latency_ms{project_name=\"$project\",cluster=\"$cluster\"}, target)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(replication_latency_replication_latency_ms{project_name=\"$project\",cluster=\"$cluster\"}, topic)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(java_Memory_HeapMemoryUsage_init{project_name=\"$project\",cluster=\"$cluster\"}, url)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "KMM Status",
   "type": "stat",
   "description": "KMM Status shows current state of kafka-mirror-maker. It can be UP,  DEGRADED, FAILED. ",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kmm_health_status_code{project_name=~\"$project\" ,cluster=\"$cluster\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kmm_health",
     "select": [
      [
       { "params": [ "status_code" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "timeseries",
   "description": "Node Status shows the amount of alive and failed instances.",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "UP",
     "expr": "min(kmm_health_alive_nodes{project_name=~\"$project\" ,cluster=\"$cluster\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "alive nodes",
     "measurement": "kmm_health",
     "select": [
      [
       { "params": [ "alive_nodes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "DOWN",
     "expr": "min(kmm_health_failed_nodes{project_name=~\"$project\" ,cluster=\"$cluster\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "failed nodes",
     "measurement": "kmm_health",
     "select": [
      [
       { "params": [ "failed_nodes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "description": "Heap Memory Usage shows the amount of memory that is using for the heap.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_url HeapMemoryUsage - Commited",
     "expr": "max(java_Memory_HeapMemoryUsage_committed{project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "committed {{url}}",
     "measurement": "jvm_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.committed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_url Heap Memory - Used",
     "expr": "max(java_Memory_HeapMemoryUsage_used{project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "used {{url}}",
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "$tag_url Heap Memory - Max",
     "expr": "max(java_Memory_HeapMemoryUsage_max{project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "max {{url}}",
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Eden Space",
   "type": "timeseries",
   "description": "Eden Space shows the amount of memory that is using for eden space. A metric value of \"-1\" means that the value is not set",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_url - Initial",
     "expr": "max(jvm_memory_pool_bytes_init{pool=\"G1 Eden Space\",project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "init {{url}}",
     "measurement": "jvm_garbage_collector",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.memoryUsageAfterGc.PS Eden Space.init"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "$tag_url - Committed",
     "expr": "max(jvm_memory_pool_bytes_committed{pool=\"G1 Eden Space\",project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed {{url}}",
     "measurement": "jvm_garbage_collector",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.memoryUsageAfterGc.PS Eden Space.committed"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "$tag_url - Used",
     "expr": "max(jvm_memory_pool_bytes_used{pool=\"G1 Eden Space\",project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used {{url}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "$tag_url - Max",
     "expr": "max(jvm_memory_pool_bytes_max{pool=\"G1 Eden Space\",project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max {{url}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "timeseries",
   "description": "Survivor Space shows the amount of memory that is using for survivor space. A metric value of \"-1\" means that the value is not set",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_url - Init",
     "expr": "max(jvm_memory_pool_bytes_committed{pool=\"G1 Survivor Space\",project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "legendFormat": "committed {{url}}",
     "measurement": "java_last_garbage_collection",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.init"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.init"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.init"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    },
    {
     "alias": "$tag_url - Commited",
     "expr": "max(jvm_memory_pool_bytes_max{pool=\"G1 Survivor Space\",project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "legendFormat": "max {{url}}",
     "measurement": "java_last_garbage_collection",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.committed"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.committed"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.committed"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    },
    {
     "alias": "$tag_url - Used",
     "expr": "max(jvm_memory_pool_bytes_used{pool=\"G1 Survivor Space\",project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "legendFormat": "used {{url}}",
     "measurement": "java_last_garbage_collection",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.used"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.used"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageBeforeGc.Par Survivor Space.used"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "G1 Young Generation" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "PS Scavenge" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "ParNew" }
     ]
    }
   ]
  },
  {
   "title": "Non-Heap Memory Usage",
   "type": "timeseries",
   "description": "Non-Heap Memory Usage shows the amount of memory that is using for non-heap area.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_url NonHeapMemoryUsage - Commited",
     "expr": "max(java_Memory_NonHeapMemoryUsage_committed{project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "committed {{url}}",
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.committed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "$tag_url Non-Heap Memory - Used",
     "expr": "max(java_Memory_NonHeapMemoryUsage_used{project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "used {{url}}",
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "description": "Metaspace shows the amount of memory that is using for metaspace.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_url - Commited",
     "expr": "max(jvm_memory_pool_bytes_committed{pool=\"Metaspace\",project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "legendFormat": "committed {{url}}",
     "measurement": "java_last_garbage_collection",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Metaspace.committed"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "$tag_url - Used",
     "expr": "max(jvm_memory_pool_bytes_used{pool=\"Metaspace\",project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "legendFormat": "used {{url}}",
     "measurement": "java_last_garbage_collection",
     "select": [
      [
       {
        "params": [
         "LastGcInfo.LastGcInfo.memoryUsageAfterGc.Metaspace.used"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "description": "Thread Count shows the amount of active threads.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_url Total Started Thread Count",
     "expr": "avg(java_Threading_TotalStartedThreadCount{project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "started threads count: {{url}} ",
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "TotalStartedThreadCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "$tag_url Daemon Thread Count",
     "expr": "avg(java_Threading_DaemonThreadCount{project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "daemon threads count: {{url}}",
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "DaemonThreadCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "$tag_url Peak Thread Count",
     "expr": "avg(java_Threading_PeakThreadCount{project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "peak threads count: {{url}}",
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "PeakThreadCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "$tag_url Thread Count",
     "expr": "avg(java_Threading_ThreadCount{project_name=~\"$project\",url=~\"$host\" ,cluster=\"$cluster\"}) by (url)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "threads count: {{url}}",
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "ThreadCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Replicated bytes",
   "type": "stat",
   "description": "Replicated bytes shows the amount of replicated bytes.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "bytes",
     "expr": "sum(bytes_byte_count{target=~\"$target*\",project_name=~\"$project\" ,cluster=\"$cluster\"})",
     "measurement": "bytes",
     "select": [
      [
       { "params": [ "byte-count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "target", "operator": "=~", "value": "/^$target$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Replicated records",
   "type": "stat",
   "description": "Replicated records shows the amount of replicated bytes.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(record_age_record_count{project_name=~\"$project\" ,cluster=\"$cluster\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "record-age",
     "select": [
      [
       { "params": [ "record-count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Record age",
   "type": "timeseries",
   "description": "Record age shows age of each record when consumed.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "record-age",
     "expr": "avg(record_age_record_age_ms{target=~\"$target*\",project_name=~\"$project\",topic=~\"$topic\" ,cluster=\"$cluster\"}) by (target,topic)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "record-age",
     "select": [
      [
       { "params": [ "record-age-ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=~", "value": "/^$topic$/" },
      { "condition": "AND", "key": "target", "operator": "=~", "value": "/^$target$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication speed per second",
   "type": "timeseries",
   "description": "Replication speed per second shows the amount of replicated bytes per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "replication-speed",
     "expr": "avg(bytes_byte_rate{target=~\"$target*\",project_name=~\"$project\",topic=~\"$topic\" ,cluster=\"$cluster\"}) by (target,topic)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "select": [
      [
       { "params": [ "byte-rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "target", "operator": "=~", "value": "/^$target$/" },
      { "condition": "AND", "key": "topic", "operator": "=~", "value": "/^$topic$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication latency",
   "type": "timeseries",
   "description": "Replication latency shows a timespan between each record's timestamp and downstream ACK.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "replication-latency",
     "expr": "avg(replication_latency_replication_latency_ms{target=~\"$target*\",project_name=~\"$project\",topic=~\"$topic\" ,cluster=\"$cluster\"}) by (target,topic)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "replication-latency",
     "select": [
      [
       { "params": [ "replication-latency-ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "target", "operator": "=~", "value": "/^$target$/" },
      { "condition": "AND", "key": "topic", "operator": "=~", "value": "/^$topic$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  }
 ]
}