# permissions for end users to edit kmmconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmmconfig-editor-role
rules:
- apiGroups:
  - netcracker.com
  resources:
  - kmmconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netcracker.com
  resources:
  - kmmconfigs/status
  verbs:
  - get
