version: '3'
services:
  operator-sdk:
    build:
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ../../kafka-services-operator:/kafka-services-operator
    working_dir: /kafka-services-operator