{{- if (eq (include "monitoring.install" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka.name" . }}-monitoring-secret
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if (eq (include "monitoring.type" .) "influxdb") }}
  sm-db-password: {{ coalesce .Values.global.secrets.monitoring.smDbPassword .Values.monitoring.smDbPassword | default "" | quote }}
  sm-db-username: {{ coalesce .Values.global.secrets.monitoring.smDbUsername .Values.monitoring.smDbUsername | default "" | quote }}
  {{- else }}
  prometheus-username: {{ coalesce .Values.global.secrets.monitoring.prometheusUsername .Values.monitoring.prometheusUsername | default "" | quote }}
  prometheus-password: {{ coalesce .Values.global.secrets.monitoring.prometheusPassword .Values.monitoring.prometheusPassword | default "" | quote }}
  {{- end }}
{{- end }}