{{- if and .Values.monitoring.lagExporter.enabled (eq (include "monitoring.install" .) "true") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kafka.name" . }}-lag-exporter-configmap
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "kafka.name" . }}-lag-exporter-configmap
data:
  application.conf: |
    kafka_exporter {
      --web.listen-address = {{ default ":9308" (printf ":%s" (toString .Values.monitoring.lagExporter.service.port)) }}
      --web.telemetry-path = {{ .Values.monitoring.lagExporter.path | default "/metrics" }}
      --refresh.metadata = {{ .Values.monitoring.lagExporter.refreshMetadata }}
      --concurrent.enable = {{ toString .Values.monitoring.lagExporter.concurrentEnable }}
      --kafka.version = {{ .Values.monitoring.lagExporter.kafkaVersion | default "" | quote }}
      --kafka.server = {{ include "lag-exporter.bootstrapServers" . }}
      --kafka.labels = {{ .Values.monitoring.lagExporter.customLabels | default "" | quote }}
      --group.filter = {{ (include "kafka-services.regexJoin" (dict "list" .Values.monitoring.lagExporter.cluster.groupWhitelist)) | default "" | quote }}
      --group.exclude = {{ (include "kafka-services.regexJoin" (dict "list" .Values.monitoring.lagExporter.cluster.groupBlacklist)) | default "" | quote }}
      --topic.filter = {{ (include "kafka-services.regexJoin" (dict "list" .Values.monitoring.lagExporter.cluster.topicWhitelist)) | default "" | quote }}
      --topic.exclude = {{ (include "kafka-services.regexJoin" (dict "list" .Values.monitoring.lagExporter.cluster.topicBlacklist)) | default "" | quote }}
      {{- if .Values.monitoring.lagExporter.offsetShowAll }}
      --no-offset.show-all
      {{- end -}}
      {{- if .Values.monitoring.lagExporter.logEnableSarama }}
      --log.enable-sarama
      {{- end -}}
      {{- if not .Values.monitoring.lagExporter.offsetShowAll }}
      --no-offset.show-all
      {{- end }}
      {{- if .Values.monitoring.lagExporter.verbosity }}
      --verbosity = {{ .Values.monitoring.lagExporter.verbosity }}
      {{- end }}
      {{- if .Values.global.tls.serverName }}
      --tls.server-name = {{ .Values.global.tls.serverName }}
      {{- end }}
      {{- if .Values.global.tls.insecureSkipTlsVerify }}
      --tls.insecure-skip-tls-verify
      {{- end }}
    }
{{- end }}