{{- if and (not .Values.operator.serviceAccount) .Values.operator.kafkaUserConfigurator.enabled (ne .Values.operator.kafkaUserConfigurator.watchNamespace .Release.Namespace) (not .Values.global.restrictedEnvironment)  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kafka.name" . }}-service-operator-kafka-users-{{ .Release.Namespace }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
    {{- with .Values.global.customLabels }}
      {{- toYaml . | nindent 4 -}}
    {{- end }}
    {{- with .Values.operator.customLabels }}
      {{- toYaml . | nindent 4 -}}
    {{- end }}
rules:
  - apiGroups:
      - {{ .Values.operator.apiGroup }}
      {{- if .Values.operator.secondaryApiGroup }}
      - {{ .Values.operator.secondaryApiGroup }}
      {{- end }}
    resources:
      - kafkausers
      - kafkausers/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      {{- if .Values.operator.kafkaUserConfigurator.secretCreatingEnabled }}
      - create
      {{- end }}
{{- end }}