{{- if (not .Values.operator.serviceAccount) }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kafka.name" . }}-service-operator
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kafka.name" . }}-service-operator
roleRef:
  kind: Role
  name: {{ template "kafka.name" . }}-service-operator
  apiGroup: rbac.authorization.k8s.io
{{- end }}