{{- if and .Values.operator.akhqConfigurator.enabled .Values.akhq.install (not .Values.global.restrictedEnvironment) }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kafka.name" . }}-service-operator-akhq-{{ .Release.Namespace }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kafka.name" . }}-service-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "kafka.name" . }}-service-operator-akhq-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}