{{- if (and (not .Values.operator.serviceAccount) .Values.kafka.getRacksFromNodeLabels) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kafka.name" . }}-service-operator
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - {{ .Values.operator.apiGroup }}
      {{- if .Values.operator.secondaryApiGroup}}
      - {{ .Values.operator.secondaryApiGroup }}
      {{- end }}
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
{{- end }}