{{- if (not .Values.operator.serviceAccount ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kafka.name" . }}-service-operator
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
{{- end }}