{{- if .Values.integrationTests.install }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.integrationTests.service.name }}-secret
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
stringData:
  {{- if and (eq .Values.global.monitoringType "influxdb") (eq (include "monitoring.install" .) "true") }}
  zabbix-user: "{{ .Values.global.secrets.integrationTests.zabbix.username }}"
  zabbix-password: "{{ .Values.global.secrets.integrationTests.zabbix.password }}"
  {{- end }}
  {{- if .Values.backupDaemon.install }}
  backup-daemon-user: "{{ .Values.global.secrets.backupDaemon.username }}"
  backup-daemon-password: "{{ .Values.global.secrets.backupDaemon.password }}"
  {{- end }}
  idp-username: "{{ .Values.global.secrets.integrationTests.idp.username }}"
  idp-password: "{{ .Values.global.secrets.integrationTests.idp.password }}"
  idp-registration-token: "{{ .Values.global.secrets.integrationTests.idp.registrationToken }}"
  prometheus-user: "{{ .Values.global.secrets.integrationTests.prometheus.user }}"
  prometheus-password: "{{ .Values.global.secrets.integrationTests.prometheus.password }}"
{{- end }}