{{- if .Values.integrationTests.install }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.integrationTests.service.name }}
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
{{- end }}