{{- if .Values.mirrorMakerMonitoring.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka.name" . }}-mirror-maker-monitoring-secret
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if (eq (include "mirrorMakerMonitoring.type" .) "influxdb") }}
  sm-db-username: {{ coalesce .Values.global.secrets.monitoring.smDbUsername .Values.mirrorMakerMonitoring.smDbUsername | default "" | quote }}
  sm-db-password: {{ coalesce .Values.global.secrets.monitoring.smDbPassword .Values.mirrorMakerMonitoring.smDbPassword | default "" | quote }}
  {{- end }}
{{- end }}
