{{- if .Values.mirrorMaker.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka.name" . }}-mirror-maker-secret
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.mirrorMaker.clusters }}
  {{ lower .name }}-kafka-username: {{ default "" .username | quote }}
  {{ lower .name }}-kafka-password: {{ default "" .password | quote }}
  {{- end }}
{{- end }}