{{- if and .Values.akhq.install .Values.akhq.schemaRegistryUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: schema-registry-secret
  labels:
    {{- include "kafka-services.defaultLabels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.global.secrets.akhq.schemaRegistryUsername | default "" | quote }}
  password: {{ .Values.global.secrets.akhq.schemaRegistryPassword | default "" | quote }}
{{- end }}