{{- if and .Values.kafka.install (not .Values.global.externalKafka.enabled) }}
{{- $install := and .Values.global.tls.enabled .Values.kafka.tls.enabled .Values.global.tls.generateCerts.enabled }}
{{- if and $install (eq (include "services.certProvider" .) "cert-manager") (not (.Values.global.tls.generateCerts.clusterIssuerName)) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "kafka.name" . }}-services-tls-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.defaultLabels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}