name: Branch Deleted
on: delete

env:
  TAG_NAME: ${{ github.event.ref }}

jobs:
  delete:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-kafka-integration-tests
            file: integration-tests/docker/Dockerfile
            context: integration-tests
          - name: qubership-kafka-crd-init
            file: crd-init/docker/Dockerfile
            context: crd-init
          - name: qubership-kafka-operator
            file: operator/Dockerfile
            context: operator
          - name: qubership-kafka-service-operator
            file: operator/Dockerfile
            context: operator
          - name: qubership-kafka-service-transfer
            file: docker-transfer/kafka-service/Dockerfile
            context: ""
          - name: qubership-kafka-transfer
            file: docker-transfer/kafka/Dockerfile
            context: ""
          - name: qubership-kafka-backup-daemon
            file: backup-daemon/docker/Dockerfile
            context: backup-daemon
          - name: qubership-kafka-monitoring
            file: monitoring/docker/Dockerfile
            context: monitoring
          - name: qubership-docker-kafka
            file: docker-kafka/docker/Dockerfile
            context: docker-kafka
          - name: qubership-docker-akhq
            file: docker-akhq/docker/Dockerfile
            context: docker-akhq
          - name: qubership-docker-kafka-lag-exporter
            file: docker-kafka-lag-exporter/docker/Dockerfile
            context: docker-kafka-lag-exporter
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Get package IDs for delete
        id: get-ids-for-delete
        uses: Netcracker/get-package-ids@v0.0.1
        with:
          component-name: ${{ matrix.component.name }}
          component-tag: ${{ env.TAG_NAME }}
          access-token: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.component.name }}
          package-type: 'container'
          package-version-ids: ${{ steps.get-ids-for-delete.outputs.ids-for-delete }}
        if: ${{ steps.get-ids-for-delete.outputs.ids-for-delete != '' }}
