name: Run Kafka Pipeline

permissions:
  contents: read
  packages: read
  actions: read

on:
  push
#  pull_request:
#    types: [opened, synchronize, reopened]
#    branches: [main]
#    paths-ignore:
#      - "docs/**"
#      - "CODE-OF-CONDUCT.md"
#      - "CONTRIBUTING.md"
#      - "LICENSE"
#      - "README.md"
#      - "SECURITY.md"
#  push:
#    branches: [main]
#    paths-ignore:
#      - "docs/**"
#      - "CODE-OF-CONDUCT.md"
#      - "CONTRIBUTING.md"
#      - "LICENSE"
#      - "README.md"
#      - "SECURITY.md"

jobs:
  check-dev-build:
    runs-on: ubuntu-latest
    outputs:
      skip_tests: ${{ steps.check.outputs.skip_tests }}
    steps:
      - name: Skip tests
        id: check
        run: |
          echo "skip_tests=true" >> $GITHUB_OUTPUT

  Wait-for-images:
    runs-on: ubuntu-latest
    needs: check-dev-build
    if: needs.check-dev-build.outputs.skip_tests == false
    outputs:
      conclusion: ${{ steps.wait.outputs.conclusion }}
    steps:
      - name: Wait for dev_build.yml to complete
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@3e428f45132119ce49d90f3770a45d4fe1d1078d # v2.0.4
        id: wait
        with:
          workflow: dev_build.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          poll-interval: 20

  Kafka-Pipeline:
    needs: [check-dev-build, Wait-for-images]
    if: always()
    uses: Netcracker/qubership-test-pipelines/.github/workflows/kafka.yaml@fix/skip_tests # v1.6.1
    with:
      repository_name: ${{ github.repository }}
      service_branch: '${{ github.head_ref || github.ref_name }}'
      pipeline_branch: 'fix/skip_tests'
      skip_tests: true
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_S3_ACCESS_KEY_SECRET: ${{ secrets.AWS_S3_ACCESS_KEY_SECRET }}