name: Run Kafka Pipeline

permissions:
  contents: read
  packages: read
  actions: read

on:
  push
#  pull_request:
#    types: [opened, synchronize, reopened]
#    branches: [main]
#    paths-ignore:
#      - "docs/**"
#      - "CODE-OF-CONDUCT.md"
#      - "CONTRIBUTING.md"
#      - "LICENSE"
#      - "README.md"
#      - "SECURITY.md"
#  push:
#    branches: [main]
#    paths-ignore:
#      - "docs/**"
#      - "CODE-OF-CONDUCT.md"
#      - "CONTRIBUTING.md"
#      - "LICENSE"
#      - "README.md"
#      - "SECURITY.md"

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      code_changed: ${{ steps.filter.outputs.code_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            code_changed:
              - '**'
              - '!docs/**'
              - '!CODE-OF-CONDUCT.md'
              - '!CONTRIBUTING.md'
              - '!LICENSE'
              - '!README.md'
              - '!SECURITY.md'

  Print-param:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Print param
        run: echo ${{ needs.changes.outputs.code_changed }}

  Wait-for-images:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.code_changed == 'true'
    outputs:
      conclusion: ${{ steps.wait.outputs.conclusion }}
    steps:
      - name: Wait for dev_build.yml to complete
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@3e428f45132119ce49d90f3770a45d4fe1d1078d # v2.0.4
        id: wait
        with:
          workflow: dev_build.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          poll-interval: 20

  Kafka-Pipeline:
    needs: [changes, Wait-for-images]
    if: always()
    uses: Netcracker/qubership-test-pipelines/.github/workflows/kafka.yaml@fix/skip_tests # v1.6.1
    with:
      repository_name: ${{ github.repository }}
      service_branch: '${{ github.head_ref || github.ref_name }}'
      pipeline_branch: 'fix/skip_tests'
      run_tests: ${{ fromJSON(needs.changes.outputs.code_changed) }}
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_S3_ACCESS_KEY_SECRET: ${{ secrets.AWS_S3_ACCESS_KEY_SECRET }}