{
 "title": "Kafka Lag Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_CINNAMON_PROMETHEUS", "label": "Cloud", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kafka_consumergroup_group_lag, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kafka_consumergroup_group_lag{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": "query_result(kafka_consumergroup_group_lag{namespace=\"$namespace\" ,cluster=\"$cluster\"})"
   },
   {
    "name": "consumer_group",
    "label": "Consumer Group",
    "query": "query_result(kafka_consumergroup_group_lag{namespace=\"$namespace\",cluster_name=\"$cluster_name\" ,cluster=\"$cluster\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "All Consumer Group Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Consumer Group Max Lag Seconds",
   "type": "timeseries",
   "description": "Max extrapolated lag in seconds for each consumer group.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(50, kafka_consumergroup_group_max_lag_seconds{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\" ,cluster=\"$cluster\"})",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag Partition Seconds",
   "type": "timeseries",
   "description": "Extrapolated lag in seconds for each partition.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(25, kafka_consumergroup_group_lag_seconds{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\" ,cluster=\"$cluster\"})",
     "legendFormat": "{{group}},{{topic}},{{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group Max Lag Offsets",
   "type": "timeseries",
   "description": "Max offset lag for each consumer group.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(50, kafka_consumergroup_group_max_lag{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\" ,cluster=\"$cluster\"})",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag Partition Offsets",
   "type": "timeseries",
   "description": "Offset lag for each consumer group per topic partition",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(25, kafka_consumergroup_group_lag{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\" ,cluster=\"$cluster\"})",
     "legendFormat": "{{group}},{{topic}},{{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag In Time Per Group Over Offset Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$consumer_group",
   "type": "timeseries",
   "description": "Shows the max lag in time on the left Y axis and max lag in offsets on the right Y axis for the current consumer group.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "repeat": "consumer_group",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kafka_consumergroup_group_max_lag_seconds{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\",cluster=\"$cluster\"}",
     "legendFormat": "Consumer group lag in time"
    },
    {
     "expr": "kafka_consumergroup_group_max_lag{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\",cluster=\"$cluster\"}",
     "legendFormat": "Consumer group lag in offsets"
    }
   ]
  },
  {
   "title": "Consumer Group Lag in Time Per Group Over Summed Offsets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$consumer_group",
   "type": "timeseries",
   "description": "Shows the max lag in time on the left Y axis. The right Y axis has the sum of latest and last consumed offsets for all the current group partitions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "repeat": "consumer_group",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_lag_seconds{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\" ,cluster=\"$cluster\"}) by (group)",
     "legendFormat": "Consumer group lag in time"
    },
    {
     "expr": "sum(kafka_consumergroup_group_offset{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\" ,cluster=\"$cluster\"})",
     "legendFormat": "Sum of group offsets"
    },
    {
     "expr": "sum((kafka_consumergroup_group_offset{namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\",cluster=\"$cluster\"} * 0)\n+ on(namespace,cluster_name,topic,partition) group_left() kafka_partition_latest_offset{namespace=\"$namespace\",cluster_name=\"$cluster_name\" ,cluster=\"$cluster\"})",
     "legendFormat": "Sum of latest offsets"
    }
   ]
  },
  {
   "title": "Kafka Lag Exporter JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "description": "Lag Exporter used JVM memory",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_memory_bytes_used{container=\"kafka-lag-exporter\" ,cluster=\"$cluster\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "timeseries",
   "description": "Lag Exporter JVM garbage collector time",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{container=\"kafka-lag-exporter\" ,cluster=\"$cluster\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Rate",
   "type": "timeseries",
   "description": "Lag Exporter JVM garbage collector rate",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{container=\"kafka-lag-exporter\" ,cluster=\"$cluster\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}